etc/freeipmi/freeipmi.conf
etc/freeipmi/freeipmi_interpret*.conf
etc/freeipmi/libipmiconsole.conf
usr/share/doc/freeipmi/* usr/share/doc/freeipmi-common
usr/share/info
usr/share/man/man5/freeipmi.conf.5
usr/share/man/man5/freeipmi_interpret*.conf.5
usr/share/man/man5/ipmi_monitoring_sensors.conf.5
usr/share/man/man5/ipmimonitoring.conf.5
usr/share/man/man5/ipmimonitoring_sensors.conf.5
usr/share/man/man5/libipmiconsole.conf.5
usr/share/man/man5/libipmimonitoring.conf.5
usr/share/man/man7/freeipmi.7
var/cache/ipmimonitoringsdrcache
